language: objective-c
before_install:
    - brew update
    - brew install mongodb
    - ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
    - launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
script: rake test
